language: node_js
stages:
  - linting
  - name: documentation
    if: branch = DEV
  - tests
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: linting
      script:
        - "npm install eslint-config-airbnb"
        - "npm info eslint-config-airbnb@latest peerDependencies --json | command sed 's/[\\{\\},]//g ; s/: /@/g' | xargs npm install"
        - "./node_modules/.bin/eslint **/*.js"
    - stage: documentation
      script: 'echo "running documentation"'
    - stage: tests
      script: 'echo "running documentation"'
    - stage: deploy
      script: 'echo "running documentation"'
